# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.predictions import Predictions  # noqa: F401,E501
from swagger_server import util


class PredictData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, symbol: str=None, predictions: List[Predictions]=None):  # noqa: E501
        """PredictData - a model defined in Swagger

        :param symbol: The symbol of this PredictData.  # noqa: E501
        :type symbol: str
        :param predictions: The predictions of this PredictData.  # noqa: E501
        :type predictions: List[Predictions]
        """
        self.swagger_types = {
            'symbol': str,
            'predictions': List[Predictions]
        }

        self.attribute_map = {
            'symbol': 'symbol',
            'predictions': 'predictions'
        }
        self._symbol = symbol
        self._predictions = predictions

    @classmethod
    def from_dict(cls, dikt) -> 'PredictData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictData of this PredictData.  # noqa: E501
        :rtype: PredictData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def symbol(self) -> str:
        """Gets the symbol of this PredictData.


        :return: The symbol of this PredictData.
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol: str):
        """Sets the symbol of this PredictData.


        :param symbol: The symbol of this PredictData.
        :type symbol: str
        """
        if symbol is None:
            raise ValueError("Invalid value for `symbol`, must not be `None`")  # noqa: E501

        self._symbol = symbol

    @property
    def predictions(self) -> List[Predictions]:
        """Gets the predictions of this PredictData.


        :return: The predictions of this PredictData.
        :rtype: List[Predictions]
        """
        return self._predictions

    @predictions.setter
    def predictions(self, predictions: List[Predictions]):
        """Sets the predictions of this PredictData.


        :param predictions: The predictions of this PredictData.
        :type predictions: List[Predictions]
        """
        if predictions is None:
            raise ValueError("Invalid value for `predictions`, must not be `None`")  # noqa: E501

        self._predictions = predictions
